# Generated by Django 4.0.4 on 2022-05-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
    ]
